export const cropNames = [
    "Kartoffeln",
    "Silomais",
    "Sommerbrauger",
    "sonst. Getreide",
    "Winterraps",
    "Winterweizen",
    "Zuckerrübe",
] as const;

export const vegetableNames = [
    "Blumenkohl|früh",
    "Blumenkohl|spät",
    "Brokkoli|früh",
    "Brokkoli|spät",
    "Chinakohl|früh",
    "Chinakohl|spät",
    "Grünkohl",
    "Kohlrabi|früh",
    "Kohlrabi|mittelfrüh/spät",
    "Kopfkohl|mittelfrüh",
    "Kopfkohl|spät",
    "Rosenkohl",
    "Rotkohl|früh",
    "Weißkohl|früh",
    "Chicoree",
    "Eissalat|spät",
    "Eissalat|(Sommer)",
    "Eissalat|früh",
    "Feldsalat",
    "Fenchel (Knollen-)",
    "Kopfsalat|früh",
    "Kopfsalat|Sommer",
    "Erbse|spät",
    "Erbse|früh",
    "Kohlrübe",
    "Meerrettich",
    "Petersilie",
    "Porree|früh",
    "Porree|spät",
    "Radies|(Sommer)",
    "Radies|früh",
    "Radies|spät",
    "Rettich|spät",
    "Rote Rübe",
    "Kopfsalat|spät",
    "Möhre|spät",
    "Möhre|früh",
    "Pastinake",
    "Schwarzwurzel",
    "Sellerie (Knollen-)",
    "Spinat|früh",
    "Spinat|spät",
    "Schnittlauch",
    "Zwiebel (Sommer-)",
    "Buschbohne|früh",
    "Buschbohne|spät",
    "Endivie",
    "Gurke (Einlege-)",
    "Rhabarber",
    "Spargel|Ertragsjahre",
    "Spargel|Pflanzjahr",
    "Zucchini|früh",
    "Zucchini|spät",
    "Zuckermais",
] as const;

export const fruitNames = [
    "Erdbeere|Dammanbau(mit Folie), ab Juni tragend",
    "Erdbeere|Dammanbau(mit Folie), mehrmals blühend und tragend",
    "Erdbeere|Flachanbau",
    "Erdbeere|Vermehrung",
    "Kernobst",
    "Steinobst",
    "Strauchbeeren",
] as const;

export const medicalPlantNames = [
    "Angelika|Anzuchtjahr|Pflanzgut",
    "Angelika|Nutzungsjahr(PF)|Wurzel",
    "Baldrian|Nutzungsjahr(DS)|Wurzel",
    "Baldrian|Nutzungsjahr(PF)|Wurzel",
    "Basilikum|Nutzungsjahr|Kraut",
    "Bohnenkraut|Nutzungsjahr|Kraut",
    "Dill|Nutzungsjahr|Kraut",
    "Dill|Nutzungsjahr|Körner",
    "Drachenkopf|Nutzungsjahr|Kraut",
    "Eibisch|Anzuchtjahr|Pflanzgut",
    "Eibisch|Nutzungsjahr(PF)|Wurzel",
    "Fenchel|1. Nutzungsjahr(DS)|Körner",
    "Fenchel|2. Nutzungsjahr|Körner",
    "Johanniskraut|1. Nutzungsjahr|Kraut",
    "Johanniskraut|2. Nutzungsjahr|Kraut",
    "Kamille|Herbst- oder Frühjahrssaat|Blüte",
    "Kümmel|Ansaatjahr|Körner",
    "Kümmel|Nutzungsjahr|Körner",
    "Liebstock|Anzuchtjahr|Pflanzgut",
    "Liebstock|Nutzungsjahr|Wurzel",
    "Majoran|Nutzungsjahr|Kraut",
    "Malve blau|Nutzungsjahr|Kraut",
    "Medizinalrhabarber|1.–3. Standjahr|Wurzel",
    "Melisse|Ansaatjahr|Kraut",
    "Melisse|1.–3. Nutzungsjahr|Kraut",
    "Pfefferminze|Anzuchtjahr|Kraut/Pflanzgut",
    "Pfefferminze|1. Nutzungsjahr|Kraut",
    "Pfefferminze|2.+3. Nutzungsjahr|Kraut",
    "Ringelblume|Nutzungsjahr|Blüte",
    "Salbei|Nutzungsjahr(DS)|Kraut",
    "Schafgarbe|2. Nutzungsjahr|Kraut",
    "Schnittsellerie|Nutzungsjahr|Kraut",
    "Spitzwegerich|1. Nutzungsjahr|Kraut",
    "Spitzwegerich|2. Nutzungsjahr|Kraut",
    "Thymian|1. Nutzungsjahr|Kraut",
    "Thymian|2. Nutzungsjahr|Kraut",
    "Wolliger Fingerhut|Nutzungsjahr(DS)|Kraut",
    "Wurzelpetersilie|Nutzungsjahr|Wurzel",

] as const;

export const agriculturalPlantNames = [
    "Ackerbohne",
    "Einjähriges Weidelgras",
    "Futtermöhren",
    "Kohlrüben",
    "Luzerne|Hauptnutzungsjahr",
    "Luzerne|weitere Nutzungsjahre",
    "Mohn",
    "Rübensamenträger|(direkte Vermehrung)",
    "Rübensamenträger|(indirekte Vermehrung)",
    "Sojabohne",
    "Spätsommersaaten",
    "Lupine",
    "Futterkohl, Markstammkohl",
    "Wiese/Weide/Mähweidegrundwasserfern",
    "Tabak",
    "Hopfen",
] as const;

export const fordderPlantNames = [
    "Ausdauerndes Weidelgras|1",
    "Einjähriges Weidelgras|1",
    "Knaulgras|1",
    "Rotklee|2",
    "Rotschwingel|1",
    "Weißes Straußgras|1",
    "Welsches Weidelgras|1",
    "Welsches Weidelgras|2",
    "Wiesenlieschgras|1",
    "Wiesenschwingel/Wiesenschweidel/Rohrglanzgras|1",
] as const;
